# Generated by Django 5.2.6 on 2025-09-05 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('accesorios', models.TextField(blank=True)),
                ('falla_declarada', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.modelo')),
                ('tipo_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Equipo Ingresado'), ('revisado', 'Revisado'), ('presupuestado', 'Presupuestado'), ('espera_repuesto', 'En Espera de Repuesto'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('presupuesto_aceptado', 'Presupuesto Aceptado'), ('entregado', 'Entregado')], default='ingresado', max_length=50)),
                ('informe', models.TextField(blank=True, verbose_name='Informe Técnico')),
                ('es_garantia', models.BooleanField(default=False)),
                ('fecha_compra_garantia', models.DateField(blank=True, null=True)),
                ('numero_factura_garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('orden_marca_garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicios.equipo')),
            ],
        ),
    ]
