# Generated by Django 5.2.6 on 2025-09-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('celular', 'Celular'), ('tablet', 'Tablet'), ('parlante', 'Parlante'), ('auricular', 'Auricular'), ('otros', 'Otros')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('accesorios', models.TextField(blank=True)),
                ('falla_declarada', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
            ],
        ),
    ]
