# Generated by Django 5.2.6 on 2025-09-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Equipo Ingresado'), ('revisado', 'Revisado'), ('presupuestado', 'Presupuestado'), ('espera_repuesto', 'En Espera de Repuesto'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('presupuesto_aceptado', 'Presupuesto Aceptado'), ('entregado', 'Entregado')], default='ingresado', max_length=50)),
                ('informe', models.TextField(blank=True, verbose_name='Informe Técnico')),
                ('es_garantia', models.BooleanField(default=False)),
                ('fecha_compra_garantia', models.DateField(blank=True, null=True)),
                ('numero_factura_garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('orden_marca_garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicios.equipo')),
            ],
        ),
    ]
